### ISSUE TITLE
[클라이언트/서버 간 코드 모듈화 문제] 서버의 html 태그삽입없이 UI영역을 어떻게 구현할 것인가.

### ISSUE THREAD

**Issue by user188245** [user188245/web_project-X#1]
# Main Topic
### 서버의 간섭없이 UI영역을 어떻게 구현할 것인가.

서로 다른 사용자는 서로 다른 시간표를 가지고 있다. 이런 이유로 사용자간에 서로 다른 UI를 서버에서 제공해줘야 하는 의무가 있다.

기존 처리방식으로는 서버단에서 서버사이드 코드에 html태그를 어떻게 마련해야 할 것인가에 관한 추가적인 고려가 요구된다. 이는 서버측에서 사용자마다 UI를 어떻게 보일 것인가를 코드로 짤 것인가에 관한 요구로 이어지므로, 결론적으로, 둘 중 하나이다.

 1. 클라이언트 개발자가 서버측 코드로 UI코딩을 해야한다.
 2. 서버측 개발자가 html UI/UX도 같이 설계해야한다.

이는 기존 계획의 [클라이언트/서버측 코드 분리개발] 원칙에 위배가 된다.

**Comment by Mulgist** [comment]
저는 일단 html에 보이기 위한 데이터의 구조, 즉 데이터베이스 모델을 먼저 구상해야한다고 생각해요.

(사실 서버쪽이 더 속편한 얘기이긴 하지만;;) 데이터베이스 모델이 만들어지면 "어떤 데이터가 기록되는데 이 데이터는 이쪽에 배치하면 좋겠다."하는 생각(자세한건 더 얘기를 해봐야 하겠지만)도 클라이언트에서 하실수도 있고, 서버쪽에서도 쉽게 데이터베이스 모델을 만들수가 있어요.

그래서 데이터베이스 모델을 대충 짜보았습니다. 이렇게 해보면 어떨까요?

테이블: User, Semester, Class, ClassTime, Period, Calendar, Memo(or Others), Grade
- User(Django에서 자동으로 만들어줌)
  - user_id
  - username
  - password
  - name
- Semester(학기)
  - semester_id
  - name
  - start_day
  - end_day
  - user_id (foreign)
- Class(과목)
  - class_id
  - name
  - professor
  - credits (학점량. 성적 아님)
  - semester_id (foreign)
- ClassTime(수업시간. 이것이 가장 메인으로 나타나는 내용)
  - classtime_id
  - class.name (foreign)
  - start_time
  - end_time (or elapsed_time)
  - class_id (foreign)
- Period(12월 1째주 같은거)
  - period_id
  - year
  - start_month
  - week
  - start_day
  - end_day
  - beyond (그 주가 달을 넘는지)
- Calendar(휴보강, 시험 등의 시간표 페이지에 표시가능한 일정)
  - calendar_id
  - class_id (foreign)
  - period_id (foreign)
  - date
  - title (일정 이름)
  - text (일정 내용)
  - start_time
  - end_time (or elapsed_time)
- Memo(Others라고 해도 됨. 과목에 대한 댓글 등을 등록할때)
  - memo_id
  - class_id (foreign)
  - date
  - period_id (foreign)
  - text
- Grade(성적)
  - grade_id
  - user_id (foreign)
  - class_id (foreign)
  - grade
  - score
  - credits (foreign)

일단 대충 만들어본거라 관계성도 더 따져보고 진행해봐야겠습니다. 혹시 더 추가하고싶은거나 이 데이터에 의문이 드시면 얘기해주세요.

**Comment by user188245** [comment]
아직은 이야기할게 많네요. 
데이터베이스 파트는 현재 개발파트에 속해있기 때문에 동적으로 테이블을 수정하거나 추가하더라도 Model,View파트에서 손보는 작업이라 손이 많이 가지 않습니다.
 
지금 핵심은 데이터베이스 구현이 완료된 상태에서 그렇다면, 유저별 다른 html문서를 생성하는 Tamplete파트를 어떻게, 누가 구현하는가 문제입니다.

여러가지 개발 모델이 있을 수 있겠지만,

1. 클라이언트 파트 코드를 서버측으로 넘긴뒤, 서버가 클라이언트 코드를 수정하여 템플릿을 만든다 (php로 따지면 \<a herf="\<?= $var ?\>" \>에 해당되는 부분을 파이썬으로 구현한다.
클라이언트는 이때 GET메소드로 완전 동기식 http통신을 한다.

2. 클라이언트쪽 파트에서 비동기적 통신으로 서버측으로 부터 View에 해당되는 딕셔너리,튜플 형태를 받는다(이때 클라이언트는 딕셔너리를 못 받으므로 서버측에서 Json이나 Xml, YAML등으로 변환해야 됨.) 

3. 아예 클라이언트에서 서버를 중개로 데이터베이스 쿼리결과에 해당되는 튜플을 받아 자바스크립트
 단에서 View를 생성한뒤 사용자 세션정보를 읽어 이에 따른 쿼리재전송을 통한 완전 비동기적 통신을 한다.

4. 조금 다른 방법으로 클라이언트 파트에서 동적 문서 파트를 서버측 코드로 마련하거나, 서버가 읽기 쉬운 의사언어로 표현한다.

1 이 채택 될경우 = 
(1) 서버측 코드로 자바스크립트로 구현된 모듈을 읽어오기 위해선, 서버측 코드에서 자바스크립트 인터프리터를 부착한뒤, 직접 자바스크립트 구문을 실행한다.  - 비효율적이나, 개발비용이 적음.

(2) 서버측에서 직접 자바스크립트로 구현된 동적 파트의 View를 서버 측 코드로 번역해서 쓴다.
-효율적이고 아직까진 개발비용이 적음.


2 가 채택 될 경우.
(1) 서버측은 로그인/회원가입시의 템플릿만 마련하면 된다. 대신 View에서 Ajax통신을 위한 개발 비용이 조금이나마 든다.
-효율적이고 약간의 개발비용이 증가.


3 이 채택 될 경우.
(1) 서버측은 더 이상 웹서버가 아닌 그저 웹 문서를 건네주며 상호 통신하는 TCP서버에 불가하다. TCP/IP 통신모델로 새롭게 웹을 구현한다. 
-비 현실적 모델, 회원가입 구현에서의 보안이 어렵다. 회원가입은 비동기통신을 해서는 안 된다.

4가 채택 될 경우.
- 1.(2) 와 결국 동일한 방법이다.

**Comment by user188245** [comment]
엄격한 개발모델을 따를것인가, 유연한 개발모델을 따를것인가에 따라 결과가 달라지겠지만,
엄격한 개발모델아래에 개발은 분업화/코드모듈화가 쉬운 대신, 각각 코드개발에 있어 코드생산비용이 증가한다는 단점이 있고,
유연한 개발모델아래에 개발은 개발유연성이 뛰어난 대신, 서버 개발자가 클라이언트쪽 코드를 이해해야하고, 클라이언트 개발자도 서버측 코드를 이해해야 한다는 점에서, 약간의 개발숙련도를 요구한다는 점이 있습니다
